Ex1
orimaro123/monday-u-exercises pull request #1
Opened 2022-05-19 08:05 UTC by orimaro123

Almost ready...

2022-05-19 12:35 UTC, orimaro123 commented
Comment #2

2022-05-22 13:58 UTC, OronMeller requested changes
Overall:
- Very nice design
- Good work with git, a lot of commits per subject of work, etc.
- Very nice documentation with the readme file
- Requirements made well, core list functionality behaves as expected.
- Bonus additions function well, confetti and validation message are cool, local storage handling works good
- Code is a bit messy, a lot of code per function, some code duplication as well (see comments of CR), functions naming doesn't always align with what the function actually do

Best Practices:

1. You should keep the same naming convention on element ids and classes : either kebab-case or CamelCase, here you mixed kebab-case and CamelCase in ids and classes
2. Should wait for document ready event 'DOMContentLoaded' before fetching / attaching event listeners and querying elements
3. Should not mix business logic and ui / visualization logic in the same functions. Keep function logic and separation of controls should to what the function is in charge of. (take a look on some of your functions: 
`addToDo`- adds an item, play animation, saves to localstorage, and style the list
`checkLocalStorage ` doesn't just "check" as if expecting a boolean, it also get items and parse them (naming is confusing)
`getTodos` - doesn't just get the list it also create elements and add them to the DOM, changes the counter, styles the list and then might change some button to inactive (naming is confusing and also logic could be more separated)
4. Should not create elements by creating their string representation from JavaScript (`'<i  class="fas fa-trash"></i>')
5. Code duplication - some chunks of code repeat themselves in your code, this is a great indicator to when you need to create more functions to insulate this functionality.

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/index.html
> +    <div class="svg hide" id="svg"> </div>
A best practice would be to create 1 `<footer>` html5 element (instead of `div class="footer">`
inside the `<footer>` you can separate as you did with 2 `<section>` elements (instead of the "footer" & "footer2" naming

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/index.html
> +        <span>You have <span class="pendingTasksCount"></span > tasks </span >
The counter "pendingTasksCount" is a unique counter in your app and should be distinct with an id instead of with a class name (better for the get logic in the JavaScript)

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/README.md
> +## Welcome to Ori's Todo list!
Very nice readme!

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +const inputBox = document.querySelector(".inputField input");
Would be better to use the id you already set to the element - `document.getElementById("input-txt")`

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +const footerSpan = document.querySelector(" .footer span ");
See comments above on footer, a better division of elements would have helped you here as well.
selecting a child element by type (span) of a parent by class (".footer") might cause bugs in the future if you'll add another span element, etc.

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +const todoElement = document.getElementById("list-element");
you fetched the same element twice - line 4 and line 9

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +todoElement.addEventListener("click", alertTask);
You have attached 2 listeners to the click of the same element "todoList" & "todoElement".
the naming is confusing and by attaching 2 functions to the same element you created a line of callbacks which might cause bugs in the future (because they happen one after the other), also the use of e.stopPropagation in one of them might stop the other from executing.  (you created a very volatile code here)

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +    return alert(item.innerText);
This is the result of attaching 2 clicks to the same container `<ul>` element..
This logic would not been necessary if you attached a 'click' event listener to each item created instead of the global list-element container

You should refactor it as it will cause troubles going forwards with the other exercises

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/index.html
> +    ></script>
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/96736630/169696677-bfd392c5-d571-4a4b-b449-9d2dde2e8f18.png">
Pay attention that adding the above scripts for animations & font increased the code size for your application by 9 times! (lottie + font = 64Kb, your script (8kb)

Achieving the confetti and delete animations could be done using regular css so this is a bit overkill for such a small exercise,  but as you already did it - at least it was done with a min.js file which is good and the use of the lottie animation function made properly.

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +    return launch_toast();
Very good, using the false condition to break out of the function if condition not met first.

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +  todoLi.innerText = todoInput.value;
should have attached the click event here for every todo item

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +  //Clear Todo Input value
would be better if it was an external function being called

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +  trashButton.innerHTML = '<i  class="fas fa-trash"></i>';
don't create elements with inline string, just get the parent and appendChild.
Also why using `<i>` element? it's mostly used to differentiate certain text from the rest of the text as "italicized" formatting. it has nothing to do with the logic you did here.

You better just set a class on the button element with css background image. if you do want another element then an `<img>` will fit better

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +    }, TRASH_ANIMATION_TIMEOUT);
Again, using the item.classList[0] to identify what you clicked on is bad practice.
you should attach click event per todo element or per delete button and should not put your trust on attached classes to know which functionality to trigger

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +  if (item.classList[0] === "clearAllBtn") {
Same as other comments about conditioning  classList to know which functionality to trigger

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +    }, TRASH_ANIMATION_TIMEOUT);
It is usually a bad practice to hold of business logic because of UI / animations.
They should not be coupled with each other.

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +      todoButton.classList.remove("inactive");
Better to extract to n external function, also notice that you use 2 naming conventions for the same aspect - in some elements you put "deactive" and some "inactive", you should have 1 clear convention - "inactive" is better

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +    sortBtn.textContent = "Sort";
Why do you set the button text from here? also, kinda unnecessary because after clearing you remove the Sort button from the UI anyway

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +  });
this chunk of code is duplicated here and in lines 241-255.
duplicated code should become a function that you can use multiple times

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +    sortBtn.textContent = "Sort 🡱";
a better way will be to attach a class with different image like an arrow up/down or similar
what does this text "[]" means?

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +    todos.reverse();
Why sort and then reverse? these are 2 consuming array functions.
sort function supports a compareFunc argument - see here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

You can use the sort to both do ascending and descending

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +  console.log(todoList.classList);
remove log

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +    trashButton.classList.add("trash-btn");
this chunk of code is duplicated 3 times across the script - consider minimizing duplications and create functions for reoccurring functionality

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +//function to be used in later projects
It's bad practice to introduce code that doesn't have a purpose.

2022-05-22 13:58 UTC, OronMeller commented on src/ex1/script.js
> +const todoElement = document.getElementById("list-element");
All of the logic of getElement / querySelector should be after document ready event to ensure the above elements are actually exist on the DOM at the time of query

2022-05-23 10:23 UTC, orimaro123 commented on src/ex1/index.html
> +    <div class="svg hide" id="svg"> </div>
done

2022-05-23 10:24 UTC, orimaro123 commented on src/ex1/README.md
> +## Welcome to Ori's Todo list!
Thanks !

2022-05-23 10:38 UTC, orimaro123 commented on src/ex1/index.html
> +        <span>You have <span class="pendingTasksCount"></span > tasks </span >
done

2022-06-14 11:22 UTC, merged